[project]
name = "infra-mock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "flask>=3.1.0",
    "jwt>=1.3.1",
    "uuid>=1.30",
]
